config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :posts do
    collection do
      post '/confirm', to: 'posts#confirm', as: :confirm
      get '/complete', to: 'posts#complete', as: :complete
    end
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :post_images
  has_many :posts, through: :post_images

  validates :extension, presence: true, image_extension: true

  attr_accessor :file, :upload_file
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_images
  has_many :images, through: :post_images

  validates :title, presence: true
  validates :description, presence: true
end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :post
  belongs_to :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  permits :file_name, :extension, :description

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create(image)
    @image = Image.new(image)

    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  # PUT /images/1
  def update(image)
    if @image.update(image)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy

    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image(id)
      @image = Image.find(id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  permits :title, :description, images: [:file_name, :description, :extension, :file]

  def index
    @posts = Post.all
  end

  def show(id)
    @post = Post.find(id)
  end

  def new
    @post = Post.new
    2.times {
      @post.images.build
    }
  end

  def confirm(post)
    images = []
    if post['images'].to_a.any?
      post['images'].each_with_index do |image, index|

s3 = Aws::S3::Client.new
response = s3.list_buckets

        if file ||= image['file']
          # File.open('./tmp/'+ file.original_filename, 'wb') do |openfile|
          #   openfile.write(file.read)
          # end

s3.put_object(
    bucket: ENV['S3_BUCKET'],
    body: file.read,
    key: file.original_filename
)

          image['upload_file'] = file
          image['file_name'] = file.original_filename
          image['extension'] = File.extname(file.original_filename)
          images[index] = Image.new(image)
        end
      end
      post['images'] = images
    end

    if images.any?
      @post = Post.new(post)
    else
      @post = Post.new(post)
    end

    unless @post.valid?
      render(:new)
    end
  end

  def create(post)
    images = []
    if post['images'].to_a.any?
      post['images'].each_with_index do |image, index|
        images[index] = Image.new(image)
      end
      post['images'] = images
    end

    if images.any?
      @post = Post.new(post)
    else
      @post = Post.new(post)
    end

    if @post.save
      redirect_to(complete_posts_url)
    else
      render(:new)
    end
  end

  def complete
  end

  def edit
  end

  def update(post)
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_uri(file)
    base64 = Base64.encode64(file.upload_file.read).gsub(/\s+/, "")
    "data:#{file.upload_file.content_type};base64,#{Rack::Utils.escape(base64)}"
  end

  def s3_url(file_name)
    "#{ENV['S3_URL']}/#{ENV['S3_BUCKET']}/#{file_name}"
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/_form.html.haml
= form_for(@image) do |f|
  - if @image.errors.any?
    #error_explanation
      %h2
        = pluralize(@image.errors.count, "error")
        prohibited this image from being saved:
      %ul
        - @image.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :file_name
    %br/
    = f.text_field :file_name
  .field
    = f.label :extension
    %br/
    = f.text_field :extension
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/images/edit.html.haml
%h1 Editing Image
= render 'form'
= link_to 'Show', @image
|
= link_to 'Back', images_path

app/views/images/index.html.haml
%p#notice= notice
%h1 Listing Images
%table
  %thead
    %tr
      %th File name
      %th Extension
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @images.each do |image|
      %tr
        %td= image.file_name
        %td= image.extension
        %td= image.description
        %td= link_to 'Show', image
        %td= link_to 'Edit', edit_image_path(image)
        %td= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New Image
= render 'form'
= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice
%p
  %strong File name:
  = @image.file_name
%p
  %strong Extension:
  = @image.extension
%p
  %strong Description:
  = @image.description
= link_to 'Edit', edit_image_path(@image)
|
= link_to 'Back', images_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PostsAndImages
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/posts/_confirm.html.haml
%h1 新規投稿

%p= @post.title
%p= @post.description

%div
  - if @post.images.to_a.any?
    - @post.images.each do |image|
      = image_tag s3_url(image.file_name)
      %br
      = image.description
      %br

= form_for @post do |f|
  = f.hidden_field(:title)
  = f.hidden_field(:description)
  - @post.images.each do |image|
    = f.fields_for 'images[]', image do |image_field|
      = image_field.hidden_field :file_name
      = image_field.hidden_field :description
      = image_field.hidden_field :extension

  =# render partial: 'hidden_params', locals: {form: f}
  = f.submit '送信する'

app/views/posts/_form.html.haml
= form_for(@post, url: confirm_posts_path) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
      %ul
        - @post.images.each do |image|
          - image.errors.full_messages.each do |message|
            %li= message

  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :images

  - @post.images.each do |image|
    %ul
      - image.errors.full_messages.each do |message|
        %li= message

    = f.fields_for 'images[]', image do |image_field|
      .field
        ファイル
        %br
        = image_field.file_field :file
      .field
        要約
        %br
        = image_field.text_area :description

  .actions
    = f.submit

app/views/posts/complete.html.haml
%h1 新規投稿（完了）

= link_to 'Back', posts_path

app/views/posts/confirm.html.haml
%h1 新規投稿（確認）

= render 'confirm'

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%p#notice= notice
%h1 Listing Posts
%table
  %thead
    %tr
      %th Title
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.description
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 新規投稿

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @post.title
%p
  %strong Description:
  = @post.description
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path